cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'bash' # macOS comes with an ancient version of bash
brew 'bat'
brew 'btop'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'mutagen'
brew 'neovim'
brew 'pure'
brew 'rbenv'
brew 'ruby-build'
brew 'tldr'
brew 'tmux'
brew 'zoxide'
brew 'zsh'
